= Specification
Gunnar Morling
:awestruct-layout: default

== Jakarta Bean Validation 2.0

Jakarta Bean Validation 2.0 was published in July 2019.
It is based on Bean Validation 2.0.

It's part of Jakarta EE 8 (but can of course be used with plain Java SE as the previous releases).

You can learn more about Jakarta Bean Validation 2.0 link:/2.0/[here] (specification text, full change log, API docs etc).

== Bean Validation 2.0

Bean Validation 2.0 (https://www.jcp.org/en/jsr/detail?id=380[JSR 380]) was finished in August 2017.

It's part of Java EE 8 (but can of course be used with plain Java SE as the previous releases).

You can learn more about Bean Validation 2.0 link:/2.0-jsr380/[here] (specification text, full change log, API docs etc).

== Bean Validation 1.1

Bean Validation 1.1 (https://www.jcp.org/en/jsr/detail?id=349[JSR 349]) was finished in 2013 and is part of Java EE 7.
Its main contributions are method-level validation, integration with CDI, group conversion and some more.
You can learn more about Bean Validation 1.1 link:/1.1/[here] (specification text, full change log, API docs etc).

== Bean Validation 1.0

Bean Validation 1.0 (https://www.jcp.org/en/jsr/detail?id=303[JSR 303]) was the first version of Java's standard for object validation.
It was released in 2009 and is part of Java EE 6.
You can learn more about Bean Validation 1.0 link:/1.0/[here] (specification text, API docs etc).
