= Bean Validation 1.1 early draft 1 is out - time for feedback
Emmanuel Bernard
:awestruct-layout: news
:awestruct-tags: [ "release" ]

After a long time in the shadows of open work... Ahem, take two. After a long time at work,
I am very pleased to announce Bean Validation 1.1 early draft 1.
This is our first big milestone since the release of 1.0.

The draft is making its way through the official channels of the JCP but
we also wanted to release it in full openned. For people in a hurry,
link:/1.1/spec/1.0.0.alpha1/?utm_source=blog&utm_medium=web&utm_content=spec&utm_campaign=1_1_edr1[the spec draft is here].

== What's new

We worked on three major areas:

* openess
* method level validation
* dependency injection

=== Openess

The specification, the reference implementation, the TCK, this website... everything is open sourced.
All work done on Bean Validation 1.1 is done in the open either on the mailing list, the issue tracker
or via GitHub pull requests. Check out more in the link:/contribute[how to contribute section].

=== Method-level validation

You can now put constraints declarations on parameters and return values of methods and constructors.

[source,java]
----
@MethodValidated 
public class OrderService {

    public OrderService(@NotNull CreditCardProcessor creditCardProcessor) {
        //...
    }

    public void placeOrder(
        @NotNull @Size(min=3, max=20) String customerCode,
        @NotNull @Valid Item item,
        @Min(1) int quantity) {

        //...
    }
}
----

Interception frameworks like CDI will check these constraints upon method calls thanks to the
`@MethodValidated` annotation. Read more in the spec.

=== Dependency injection

Bean Validation uses a few components `MessageInterpolator`, `TraversableResolver`, `ConstraintValidatorFactory`
and most importantly `ConstraintValidator`. We have standardized how these objects are managed by a container
and how these objects can benefit from container services.

That means that your constraint validator implementation will be able to get resources injected automatically.

While we go into details on how it will fit in CDI and Java EE, we have worked hard to make it container
agnostic. If you write or use other containers (Guice, Spring Framework, Avalon :) ), check out
if it fits properly.

== Contributions

We have had tremendous help from the Bean Validation community at large but I would
like to give a massive thank you to link:http://musingsofaprogrammingaddict.blogspot.com/[Gunnar Morling] who stepped
up and lead the work on method-level validation. This is by far the biggest new
feature of Bean Validation 1.1.

== How to read the spec and provide feedback

The draft has been published link:/1.1/spec/1.0.0.alpha1/?utm_source=blog&utm_medium=web&utm_content=spec&utm_campaign=1_1_edr1[here] and all changes are marked with a different
color. [green]#Green for additions#, [yellow]#yellow for changes# and [red]#struck through red for removals#. This will help you see what has changed precisely.

Have feedback? Please talk to us either:

* on our link:https://lists.jboss.org/mailman/listinfo/beanvalidation-dev[mailing list]
* in our link:/issues[issue tracker]
* or on the Bean Validation link:https://discourse.hibernate.org/c/bean-validation[forum]

If you want to go to the next step and contribute, send us an email to the mailing list and read
link:/contribute[how to contribute].
