= Big push on Bean Validation 1.1
Emmanuel Bernard
:awestruct-layout: news
:awestruct-tags: [ "status-update" ]

Like most of you, the Bean Validation specification is coming back from holiday
fresh and motivated.

Java EE 7 is coming soon and to avoid missing the train, it is time to reap the fruits of all the discussions
we have had over the last few months. I expect September and October to be focused
on:

* integrating the various proposals in the speficication and flesh out
the remaining problems
* taking decisions to unstuck discussions
* iterating over the features proposed in the early draft
(we have had good feedback from the JAX-RS expert group to refine
method validation)

The rest of the time will be focused on writing the reference implementation
and the TCK and refine the various new features.
We will also work with other expert groups to clarify the integration (CDI,
JAX-RS, Java EE...).

Our priority list is link:/roadmap/#priorities[published] in the open. We will probably adjust it
a bit but the main lines are now fixed. If you feel that something important is missing,
come and help us identify it and build it.

And remember, if you come later and complain about Bean Validation, we will ask you:
link:/contribute/[where] link:https://github.com/beanvalidation/beanvalidation-spec[were]
link:https://github.com/hibernate/hibernate-validator[you]? ;)
