= Training materials on Bean Validation 1.1
Emmanuel Bernard
:awestruct-layout: news
:awestruct-tags: [ "training" ]

I have two good Bean Validation related content for you today.

== Training slides (in French)

Laurent Guerin wrote a comprehensive training on Bean Validation (1.0 and 1.1) for French students.
The http://fr.slideshare.net/lguerin/cours-javabean-validationv11[slides are available] under a Creative Commons license.
I did review them and they are very good.

The bad news is that they are in French.
The good news is that they are in French!

== Video training (in English)

Antonio Goncalves, my esteemed co-host of http://lescastcodeurs.com[Les Cast Codeurs] has published
a http://pluralsight.com/training/Courses/Description/bean-validation[2 and a half hour video training] on Bean Validation.
It is hosted on Pluralsight where packages start at $29 / month but you can get the first 10 days free.

The good news is that Antonio has a Dr Love / French accent combo voice.
The bad news? I'll let you find out ;)

Let me know if you have found good materials on Bean Validation.
We might start a dedicated page on the website.
