= Bean Validation TCKs now with signature files for Java SE 8
Gunnar Morling
:awestruct-layout: news
:awestruct-tags: [ "tck" ]

Good news for those of you who want to certify the compatibility of a Bean Validation
implementation (and its API JAR) against Java SE 8.

We have released updates to the Bean Validation TCK 1.0 and 1.1;
The versions are 1.0.7.GA and 1.1.3.Final, respectively.
Both TCK releases come now with a version of the API signature file which works with Java SE 8.
This signature file can be used to assert API compatibility with JSR 303/349 via
the https://wiki.openjdk.java.net/display/CodeTools/SigTest[SigTest] tool.
SigTest 3.0 needs to be used from now on. Note that the actual tests of the TCKs remain unchanged.

You can get distribution bundles with the new signature file from SourceForge
(http://sourceforge.net/projects/hibernate/files/beanvalidation-tck/1.0.7.GA/[1.0],
http://sourceforge.net/projects/hibernate/files/beanvalidation-tck/1.1.3.Final/[1.1]).

More information about the Bean Validation TCK can be found http://beanvalidation.org/1.1/tck/[here].
Refer to the TCK reference guide
(https://docs.jboss.org/hibernate/beanvalidation/tck/1.0/reference/html_single/#sigtest[1.0],
https://docs.jboss.org/hibernate/beanvalidation/tck/1.1/reference/html_single/#sigtest[1.1])
if you would like to learn more about the process of asserting API compatibility.

Don't hesitate to https://lists.jboss.org/mailman/listinfo/beanvalidation-dev[contact us]
in case you have any questions around the Bean Validation specification in general or the TCK
in particular.
