= How to contribute a specification proposal
Emmanuel Bernard
:awestruct-layout: default

The specification proper is written in http://www.methods.co.nz/asciidoc/[AsciiDoc], a mark-up language geared towards good source readability as well as nice rendering.

The recommended approach to contribute to the spec is via
http://help.github.com/send-pull-requests/[GitHub pull requests].
This is an extremely useful tool to review and comment proposals.

Many specification changes involve API changes as well. In this case, propose a pull
request for the https://github.com/jakartaee/validation[Jakarta Validation API]
repository as well. When doing so, make sure to follow our link:/contribute/coding[coding guidelines].

Want to be a very good citizen? Also work on implementing your proposal on the
https://github.com/hibernate/hibernate-validator[reference implementation] and the
https://github.com/jakartaee/validation-tck[TCK] and send a pull request for each. Easy :)

== Pull requests

Some basic info on http://help.github.com/send-pull-requests/[pull requests].

When doing a pull request, make sure to:

* rebase your work off the latest master
* name your topic branch by the issue number
  (like https://hibernate.atlassian.net/browse/BVAL-42[BVAL-42])
* rebase your work rather than merge, non linear histories are annoying
* respect the style (coding, number of columns per line etc)

== Recommended tools to edit the AsciiDoc specification

Refer to the http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/[tips on asciidoctor.org] for AsciiDoc tooling including live previews.
