---
title: Bean Validation 1.1 Specification
layout: default
author: Emmanuel Bernard
---

You can read the link:spec/[full Bean Validation 1.1 specification] or browse its
http://docs.jboss.org/hibernate/beanvalidation/spec/1.1/api/[API JavaDocs].

== Changes between Bean Validation 1.0 and 1.1

Bean Validation 1.1 focused on the following topics:

- openness of the specification and its process
- method-level validation (validation of parameters or return values)
- dependency injection for Bean Validation components
- integration with Context and Dependency Injection (CDI)
- group conversion
- error message interpolation using EL expressions

For more information, check out the link:changes/[full list of goals and changes].

== History

If you are interested in the various drafts that led to Bean Validation 1.1, check
out the link:history/[history page].

== Feedback

Do you have feedback? Talk to us:

- on our https://lists.jboss.org/mailman/listinfo/beanvalidation-dev[mailing list]
- in our https://hibernate.atlassian.net/browse/BVAL[issue tracker]
- or on the https://forum.hibernate.org/viewforum.php?f=26[Bean Validation forum]

If you want to take the next step and contribute, read link:/contribute[how to contribute].
